import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import '@/ui/styles/base/globals.scss'
import Navbar from '@/ui/components/navbar/Navbar'
import Footer from '@/ui/components/footer/Footer'

const inter = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Thomas rey Fs Dev',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} layout`}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
