import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import '@/ui/styles/base/globals.scss'
import { Providers } from '@/libs/redux/provider/Provider'
import Navbar from '@/ui/components/navbar/Navbar'
import Footer from '@/ui/components/footer/Footer'

const poppins = Poppins({ weight: "400", subsets:["latin"] })

export const metadata: Metadata = {
  title: 'Thomas rey Fs Dev',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Providers>
      <html lang="en">
        <body className={`${poppins.className} layout`}>
          <Navbar/>
          {children}
          <Footer/>
        </body>
      </html>
    </Providers>
  )
}
